-- =============================================================
-- SST MANAGER 3.0 - ESQUEMA SUPABASE
-- Ejecutar PRIMERO en Supabase > SQL Editor
-- =============================================================

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.trabajadores (
  id bigint generated by default as identity primary key,
  dni text not null unique check (dni ~ '^[0-9]{8}$'),
  nombre_completo text not null,
  puesto text not null default '.',
  area text not null default '.',
  fecha_ingreso date,
  estado text not null default 'Activo' check (estado in ('Activo','Inactivo')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.emos (
  id uuid primary key default gen_random_uuid(),
  dni text not null references public.trabajadores(dni) on update cascade on delete restrict,
  fecha_examen date not null,
  aptitud text not null check (aptitud in ('Apto','Apto con restricciones','Observado','No apto')),
  detalle_restriccion text not null default 'Ninguna',
  documento_key text,
  documento_nombre text,
  documento_tipo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (dni, fecha_examen)
);

create table if not exists public.epps (
  id uuid primary key default gen_random_uuid(),
  dni text not null unique references public.trabajadores(dni) on update cascade on delete restrict,
  zapato_seguridad text not null default 'Pendiente' check (zapato_seguridad in ('Pendiente','Entregado')),
  fecha_zapato date,
  ropa_trabajo text not null default 'Pendiente' check (ropa_trabajo in ('Pendiente','Entregado')),
  fecha_ropa date,
  casco text not null default 'Pendiente' check (casco in ('Pendiente','Entregado')),
  fecha_casco date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.capacitaciones (
  id uuid primary key default gen_random_uuid(),
  dni text not null references public.trabajadores(dni) on update cascade on delete restrict,
  tema_capacitacion text not null,
  fecha_programada date not null,
  asistio text not null default 'No' check (asistio in ('Si','No')),
  fecha_asistencia date,
  created_at timestamptz not null default now(),
  unique (dni, tema_capacitacion, fecha_programada)
);

create table if not exists public.inducciones (
  id uuid primary key default gen_random_uuid(),
  dni text not null unique references public.trabajadores(dni) on update cascade on delete restrict,
  recibio_induccion text not null default 'Pendiente' check (recibio_induccion in ('Recibida','Pendiente')),
  fecha_induccion date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.risst (
  id uuid primary key default gen_random_uuid(),
  dni text not null unique references public.trabajadores(dni) on update cascade on delete restrict,
  se_entrego_risst text not null default 'No' check (se_entrego_risst in ('Si','No')),
  fecha_entrega date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.actos_inseguros (
  id uuid primary key default gen_random_uuid(),
  dni text not null references public.trabajadores(dni) on update cascade on delete restrict,
  fecha_inspeccion date not null,
  acto_inseguro_cometido text not null,
  detalle_motivo text,
  medida_correctiva text,
  created_at timestamptz not null default now()
);

create table if not exists public.iperc (
  id uuid primary key default gen_random_uuid(),
  dni text not null references public.trabajadores(dni) on update cascade on delete restrict,
  fecha date not null,
  elaboro_iperc text not null check (elaboro_iperc in ('Si','No')),
  created_at timestamptz not null default now(),
  unique (dni, fecha)
);

create table if not exists public.ptar (
  id uuid primary key default gen_random_uuid(),
  dni text not null references public.trabajadores(dni) on update cascade on delete restrict,
  fecha date not null,
  requiere_ptar text not null check (requiere_ptar in ('Si','No')),
  elaboro_ptar text not null check (elaboro_ptar in ('Si','No','No aplica')),
  created_at timestamptz not null default now(),
  unique (dni, fecha)
);

create table if not exists public.vigilancia_medica (
  id uuid primary key default gen_random_uuid(),
  dni text not null unique references public.trabajadores(dni) on update cascade on delete restrict,
  enfermedad_previa text not null default 'Ninguna',
  requiere_vigilancia text not null default 'No' check (requiere_vigilancia in ('Si','No')),
  detalle_vigilancia text not null default 'N/A',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vacunas (
  id uuid primary key default gen_random_uuid(),
  dni text not null unique references public.trabajadores(dni) on update cascade on delete restrict,
  hepatitis_estado text not null default 'Pendiente' check (hepatitis_estado in ('Pendiente','Aplicada','No aplica')),
  hepatitis_fecha date,
  influenza_estado text not null default 'Pendiente' check (influenza_estado in ('Pendiente','Aplicada','No aplica')),
  influenza_fecha date,
  tetanos_estado text not null default 'Pendiente' check (tetanos_estado in ('Pendiente','Aplicada','No aplica')),
  tetanos_fecha date,
  covid_estado text not null default 'Pendiente' check (covid_estado in ('Pendiente','Aplicada','No aplica')),
  covid_fecha date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_emos_dni_fecha on public.emos (dni, fecha_examen desc);
create index if not exists idx_cap_dni_fecha on public.capacitaciones (dni, fecha_programada desc);
create index if not exists idx_actos_dni_fecha on public.actos_inseguros (dni, fecha_inspeccion desc);
create index if not exists idx_iperc_dni_fecha on public.iperc (dni, fecha desc);
create index if not exists idx_ptar_dni_fecha on public.ptar (dni, fecha desc);

drop trigger if exists trg_trabajadores_updated_at on public.trabajadores;
create trigger trg_trabajadores_updated_at before update on public.trabajadores
for each row execute function public.set_updated_at();

drop trigger if exists trg_emos_updated_at on public.emos;
create trigger trg_emos_updated_at before update on public.emos
for each row execute function public.set_updated_at();

drop trigger if exists trg_epps_updated_at on public.epps;
create trigger trg_epps_updated_at before update on public.epps
for each row execute function public.set_updated_at();

drop trigger if exists trg_inducciones_updated_at on public.inducciones;
create trigger trg_inducciones_updated_at before update on public.inducciones
for each row execute function public.set_updated_at();

drop trigger if exists trg_risst_updated_at on public.risst;
create trigger trg_risst_updated_at before update on public.risst
for each row execute function public.set_updated_at();

drop trigger if exists trg_vigilancia_updated_at on public.vigilancia_medica;
create trigger trg_vigilancia_updated_at before update on public.vigilancia_medica
for each row execute function public.set_updated_at();

drop trigger if exists trg_vacunas_updated_at on public.vacunas;
create trigger trg_vacunas_updated_at before update on public.vacunas
for each row execute function public.set_updated_at();

-- RLS: solamente usuarios que hayan iniciado sesión en Supabase Auth.
do $$
declare t text;
begin
  foreach t in array array[
    'trabajadores','emos','epps','capacitaciones','inducciones','risst',
    'actos_inseguros','iperc','ptar','vigilancia_medica','vacunas'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "sst_authenticated_select" on public.%I', t);
    execute format('drop policy if exists "sst_authenticated_insert" on public.%I', t);
    execute format('drop policy if exists "sst_authenticated_update" on public.%I', t);
    execute format('drop policy if exists "sst_authenticated_delete" on public.%I', t);
    execute format('create policy "sst_authenticated_select" on public.%I for select to authenticated using (true)', t);
    execute format('create policy "sst_authenticated_insert" on public.%I for insert to authenticated with check (true)', t);
    execute format('create policy "sst_authenticated_update" on public.%I for update to authenticated using (true) with check (true)', t);
    execute format('create policy "sst_authenticated_delete" on public.%I for delete to authenticated using (true)', t);
  end loop;
end $$;

commit;
